/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import jp.ac.uryukyu.ie.e205710_e215749.Experiment;
import jp.ac.uryukyu.ie.e205710_e215749.FiveBatlle;


/**
 * メインクラス。ゲームを実行する。
 */
public class Main{
    /**
     * experiment() ゲームの説明をするメソッド。
     * fiveBatlle() ジャンケンゲームを初期化してスタートさせるメソッド。
     * @param args　使用しない
     */
    public static void main(String[] args){
        Experiment ex = new Experiment();
        ex.experiment();
        FiveBatlle battle = new FiveBatlle();
        battle.fiveBatlle();
        
    }


}